---
name: plag

director_uuid: <%= bosh status --uuid %>

releases:
  - name: plag
    version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

jobs:
  - name: plag
    instances: 1
    vm_type: n1-standard-1
    stemcell: trusty
    lifecycle: service
    azs:
    - z1
    networks:
    - name: default
    jobs:
    - name: plag
      release: plag
    properties:
      plag:
        metrics:
          - message:
            datadog-api-key:
            datadog-app-key:
            datadog-metric-name:
            log-file:

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
