#!/bin/bash
 
set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/tscolari/plag \

  # separate these so gosub doesn't asplode
  gosub list -test github.com/tscolari/plag/...

} > /tmp/packages

cat /tmp/packages | xargs gosub sync
